name: Release
run-name: ${{ inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. v1.2.3, v1.2.3-pre.1)'
        type: string
        required: true

jobs:
  Config:
    runs-on: ubuntu-latest
    # version (v1.2.3, v1.2.3-9-adfh), release-name (unstable, stable, v1.2.3)
    outputs:
      tagged-release: ${{ steps.provided.outputs.version && true }}
      version: ${{ steps.provided.outputs.version || steps.derived.outputs.version }}
      release-name: ${{ steps.provided.outputs.release-name || steps.derived.outputs.release-name }}
      stable: ${{ steps.provided.outputs.stable }}
      pre-release: ${{ steps.provided.outputs.pre-release || steps.derived.outputs.pre-release }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate provided version
        if: "${{ inputs.version != '' }}"
        id: provided
        run: |
          if ! echo "${{ inputs.version }}" | grep -qE '^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+(-pre\.[[:digit:]]+)?$'; then
            echo "::error::The supplied version (${{ inputs.version }}) is not a valid version string."
            exit 1
          fi
          if echo "${{ inputs.version }}" | grep -qE '^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+-pre\.[[:digit:]]+$'; then
            echo "pre-release=true" >> $GITHUB_OUTPUT
          else
            echo "pre-release=false" >> $GITHUB_OUTPUT
            echo "stable=true" >> $GITHUB_OUTPUT
          fi
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "release-name=${{ inputs.version }}" >> $GITHUB_OUTPUT
          echo "release-sha=${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Derive version
        if: "${{ inputs.version == '' }}"
        id: derived
        run: |
          echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT
          echo "release-name=unstable" >> $GITHUB_OUTPUT
          echo "release-sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "pre-release=true" >> $GITHUB_OUTPUT
  #Test:
  #  uses: eval/bangbanggo/.github/workflows/test.yml@main
  Build:
    needs: [Config]
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache js deps
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2

      - name: Setup
        run: yarn setup
      - name: Compile
        run: yarn ext:release

      - name: Update VERSION
        run: echo "${{ needs.Config.outputs.version }}" > ext/VERSION
      - name: Zip it
        run: |
          mv ext bbg-${{ needs.Config.outputs.version }}
          zip -r bangbanggo-${{ needs.Config.outputs.version }}.zip bbg-${{ needs.Config.outputs.version }}
          cp bangbanggo-${{ needs.Config.outputs.version }}.zip bangbanggo-latest.zip
      - name: Tagged release
        if: "${{ needs.Config.outputs.tagged-release }}"
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Info

            - version: ${{ needs.Config.outputs.version }}
            - SHA: ${{ github.sha }}
          prerelease: ${{ needs.Config.outputs.pre-release }}
          name: ${{ needs.Config.outputs.release-name }}
          target_commitish: ${{ github.sha }}
          tag_name: ${{ needs.Config.outputs.release-name }}
          files: |
            bangbanggo-${{ needs.Config.outputs.version }}.zip
